wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1639010287
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 1
      - 16
      4: 3.7.11
      5: 0.12.7
      6: 4.12.5
      8:
      - 5
data_config:
  desc: null
  value: DataArguments(data_path='../data/LABEL_CHALLENGER_I_MatchData_last20_Ver3.csv',
    label_path='../data/LABEL_CHALLENGER_I_MatchData_last20_Ver3.csv')
model_config:
  desc: null
  value: ModelArguments(input_dim=350, output_dim=2, n_steps=4, n_d=16, n_a=16, learning_rate=0.01,
    epochs=5000, self_supervised_learning_epochs=1, l_sparse=1e-06, gamma=1.5, batch_size=4096,
    n_independent=2, n_shared=2, epsilon=1e-15, virtual_batch_size=128, momentum=0.95)
